### ISSUE TITLE
Building operation from list stalls compiler

### ISSUE THREAD

**Issue by xtian** [dillonkearns/graphqelm#36] opened 2018-02-07 00:01 UTC
This seems like a compiler bug but I thought I'd report it here first, at least for reference purposes.

I was trying to do something like this to build a batch of mutations into a single request:

```elm
ids
    |> List.map (\id -> Api.Mutation.deleteFoo { id = Api.Scalar.Id id } SelectionSet.empty)
    |> List.foldl SelectionSet.with (Api.Mutation.selection identity)
    |> Graphqelm.Http.mutationRequest "…"
    |> Graphqelm.Http.toTask
```

However this code puts compiler into an infinite loop (as far as I can tell).

Feel free to close if you think there's nothing to be done at the Graphqelm level and I'll open an issue on the compiler.

**Comment by dillonkearns** [comment] 2018-02-07 00:10
Hmm, yeah that's pretty odd. I'm not sure how to understand this better as I was able to use `Graphqelm.Http.toTask` without any issues.

Maybe to get more information on this you could try a few things, like
* Try it with a regular Http.send
* Try building up a regular Elm http request to the endpoint and see if you can reproduce it by sending [`Http.toTask`](http://package.elm-lang.org/packages/elm-lang/http/1.0.0/Http#toTask).

Thanks for opening the issue, it's good to have this here for reference in case anyone else runs into this. Let me know what you learn. I'm more than happy to help debug however I can, but beyond that I don't think there's much I can do since as you say, so I'll close this out. The [`Graphqelm.Http` code](https://github.com/dillonkearns/graphqelm/blob/49a8d6f7cdb034918ec87c603be262a76c95f6ab/src/Graphqelm/Http.elm#L241-L251) isn't doing anything to intricate, just converting it to an `Http.Request` internally and then calling `Http.toTask`.

**Closed by dillonkearns** 2018-02-07 00:10 UTC

**Comment by dillonkearns** [comment] 2018-02-07 00:43
Also @xtian, wouldn't it be pretty straightforward to build that up as a single Mutation? Or do you need to ensure that the order of the operations is what you want it to be maybe?

I'm also hoping to add a `SelectionSet.combine` function that will make this even simpler. (There are a few technical difficulties in doing this and I'll be on vacation for a couple of weeks so it might take a little while to get that out, though).

**Comment by xtian** [comment] 2018-02-07 04:29
Yeah it's not the `toTask` part that is the problem as far as I know. I think the `Http` code is unrelated to this issue. It seems to be the `foldl` that is problematic, although I haven't completely isolated the conditions under which this happens.

**Comment by xtian** [comment] 2018-02-17 17:12
@dillonkearns Here's some code that reproduces this issue using [the Star Wars example on Ellie][sw-example]:

```elm
query : SelectionSet Response RootQuery
query =
    let
        -- Imagine that `ids` is built dynamically from user input
        ids = ["1004", "1001"]
    in
        ids
            |> List.map (\id -> Query.human { id = Swapi.Scalar.Id id } human)
            |> List.foldl with (Query.selection identity)
```

(I would share a link but this code crashes the browser tab when a save is attempted)

[sw-example]: https://rebrand.ly/graphqelm
